/* generated by idc -- the `id` language compiler */
#define _POSIX_C_SOURCE 200809L
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <stdint.h>
#include <limits.h>
#include <termios.h>
#include <unistd.h>
#include <time.h>

/* ---- allocation arena -----------------------------------------------------
   Every heap block the runtime allocates (list headers/cells, and the C
   strings built by concat/str_of_int/str_of_float/input/read_all/chr) is
   wrapped with a small intrusive header and linked into one list, so the
   whole arena can be released in a single pass at process exit (the free-all
   is registered with atexit on the first allocation). id programs never call
   free() themselves, so without this a long-running program (e.g. string
   concatenation in a loop) would leak every intermediate string forever;
   with it, nothing outlives the process. This bounds *leaks*, not *peak*
   memory during the run -- a program that builds one huge string still holds
   every intermediate allocation live until exit, same as before this change.
   Every allocation in this file goes through id_alloc/id_realloc below, which
   also check for allocation failure and for size-computation overflow,
   aborting with a clear message instead of continuing with a NULL pointer or
   a wrapped-around size. */
typedef struct IdAllocHdr { struct IdAllocHdr* prev; struct IdAllocHdr* next; } IdAllocHdr;
static IdAllocHdr* id_arena_head = NULL;
static int id_arena_hooked = 0;
static void id_arena_free_all(void) {
    IdAllocHdr* h = id_arena_head;
    while (h) { IdAllocHdr* nx = h->next; free(h); h = nx; }
    id_arena_head = NULL;
}
static void id_arena_link(IdAllocHdr* h) {
    h->prev = NULL;
    h->next = id_arena_head;
    if (id_arena_head) id_arena_head->prev = h;
    id_arena_head = h;
    if (!id_arena_hooked) { atexit(id_arena_free_all); id_arena_hooked = 1; }
}
static void id_arena_unlink(IdAllocHdr* h) {
    if (h->prev) h->prev->next = h->next; else id_arena_head = h->next;
    if (h->next) h->next->prev = h->prev;
}
static size_t id_add_check(size_t a, size_t b, const char* what) {
    if (a > SIZE_MAX - b) {
        fprintf(stderr, "id: allocation size overflow (%s)\n", what);
        exit(1);
    }
    return a + b;
}
static size_t id_mul_check(size_t a, size_t b, const char* what) {
    if (a != 0 && b > SIZE_MAX / a) {
        fprintf(stderr, "id: allocation size overflow (%s)\n", what);
        exit(1);
    }
    return a * b;
}
/* String lengths, remembered.
   A `string` is a NUL-terminated char*, so its length is a strlen -- and every
   id program walks text with charat, which needs the length to know where the
   end is. One remembered length made a single scan O(n) instead of O(n^2). It
   did not make *two* scans O(n): a parser that reads its input and builds a
   string alternates between two pointers, misses the memo on every call, and
   pays a strlen of the whole input per character. Measured on an OpenDocument
   content.xml, that was 46.8 seconds for 3.5 MB.
   So the memo holds several. ID_LEN_MEMO is the number of strings that may be
   walked at once before the cost comes back; eight covers a parser reading one
   input while building a name and comparing against a keyword, with room over.
   Raising it costs one pointer comparison per miss.
   The real answer is a string that carries its own length, which would remove
   the question rather than bound it -- and which means changing how a literal
   is emitted, so it is a decision about the language rather than about this
   file. See docs/FRICTION.md. */
#define ID_LEN_MEMO 8
static const char* id_lm_s[ID_LEN_MEMO];
static size_t id_lm_n[ID_LEN_MEMO];
static unsigned id_lm_at = 0;
static size_t id_slen(const char* s) {
    unsigned i;
    for (i = 0; i < ID_LEN_MEMO; i++) if (id_lm_s[i] == s) return id_lm_n[i];
    i = id_lm_at;
    id_lm_at = (id_lm_at + 1) % ID_LEN_MEMO;
    id_lm_s[i] = s;
    id_lm_n[i] = strlen(s);
    return id_lm_n[i];
}
/* A block that moved may be reused by a later string at the same address, so
   every remembered length has to go with it. Only when it actually moved: a
   realloc that grows in place invalidates nothing. */
static void id_lm_forget(void) {
    unsigned i;
    for (i = 0; i < ID_LEN_MEMO; i++) id_lm_s[i] = NULL;
}
static void* id_alloc(size_t n) {
    IdAllocHdr* h = (IdAllocHdr*)malloc(id_add_check(n, sizeof(IdAllocHdr), "alloc"));
    if (!h) { fprintf(stderr, "id: out of memory (%zu bytes)\n", n); exit(1); }
    id_arena_link(h);
    return (void*)(h + 1);
}
static void* id_realloc(void* p, size_t n) {
    if (!p) return id_alloc(n);
    IdAllocHdr* h = (IdAllocHdr*)p - 1;
    id_arena_unlink(h);
    IdAllocHdr* nh = (IdAllocHdr*)realloc(h, id_add_check(n, sizeof(IdAllocHdr), "realloc"));
    if (!nh) { fprintf(stderr, "id: out of memory (%zu bytes)\n", n); exit(1); }
    if (nh != h) id_lm_forget();
    id_arena_link(nh);
    return (void*)(nh + 1);
}

/* Growable, heap-allocated, reference-semantic list. Every element is stored
   in a uniform 8-byte cell; the compiler boxes/unboxes per the static element
   type. Because a list is a pointer, passing one to a function and mutating it
   is visible to the caller -- this is how id gets shared mutable state.
   Every index access is bounds-checked: an out-of-range get/set/pop is a
   clear, fatal runtime error (never silent corruption or UB), matching id's
   contract that a bug aborts loudly instead of reading/writing garbage. */
typedef struct { int len, cap; long long* data; } IdList;
static IdList* id_list_new(void) {
    IdList* L = (IdList*)id_alloc(sizeof(IdList));
    L->len = 0; L->cap = 4;
    L->data = (long long*)id_alloc(id_mul_check(sizeof(long long), (size_t)L->cap, "list init"));
    return L;
}
static void id_list_push(IdList* L, long long v) {
    if (L->len >= L->cap) {
        if (L->cap > INT_MAX / 2) {
            fprintf(stderr, "id: list capacity overflow\n");
            exit(1);
        }
        int ncap = L->cap * 2;
        L->data = (long long*)id_realloc(L->data,
            id_mul_check(sizeof(long long), (size_t)ncap, "list growth"));
        L->cap = ncap;
    }
    L->data[L->len++] = v;
}
static long long id_list_get(IdList* L, int i) {
    if (i < 0 || i >= L->len) {
        fprintf(stderr, "id: index %d out of bounds (len %d)\n", i, L->len);
        exit(1);
    }
    return L->data[i];
}
static void id_list_set(IdList* L, int i, long long v) {
    if (i < 0 || i >= L->len) {
        fprintf(stderr, "id: index %d out of bounds (len %d)\n", i, L->len);
        exit(1);
    }
    L->data[i] = v;
}
static int id_list_len(IdList* L) { return L->len; }
static long long id_list_pop(IdList* L) {   /* remove & return the last cell */
    if (L->len <= 0) {
        fprintf(stderr, "id: pop from empty list\n");
        exit(1);
    }
    return L->data[--L->len];
}
static IdList* id_list_lit(int n, ...) {   /* elements are pre-boxed to cells */
    IdList* L = id_list_new();
    va_list ap; va_start(ap, n);
    for (int k = 0; k < n; k++) id_list_push(L, va_arg(ap, long long));
    va_end(ap);
    return L;
}
static long long id_box_f(double d) { long long x; memcpy(&x, &d, 8); return x; }
static double id_unbox_f(long long x) { double d; memcpy(&d, &x, 8); return d; }
static int id_to_int(const char* s) { return atoi(s); }

static char* id_concat(const char* a, const char* b) {
    size_t la = strlen(a), lb = strlen(b);
    size_t n = id_add_check(id_add_check(la, lb, "concat"), 1, "concat");
    char* r = (char*)id_alloc(n);
    memcpy(r, a, la);
    memcpy(r + la, b, lb + 1);
    return r;
}
static char* id_str_of_int(int x) {
    char* r = (char*)id_alloc(32); snprintf(r, 32, "%d", x); return r;
}
static char* id_str_of_word(long long x) {
    char* r = (char*)id_alloc(32); snprintf(r, 32, "%lld", x); return r;
}

/* ---- word arithmetic with no undefined behaviour ------------------------
   C leaves division by zero, INT_MIN/-1, and shifts by 64-or-more undefined.
   id gives all three a defined answer -- a loud abort for the first two,
   which are always bugs, and the obvious result for the third -- on the same
   principle as bounds-checked list indexing: a mistake stops the program
   instead of quietly producing nonsense. */
static void id_trap(const char* what) {
    fprintf(stderr, "id: %s\n", what);
    exit(1);
}
static long long id_sdiv(long long a, long long b) {
    if (b == 0) id_trap("division by zero");
    if (b == -1 && a == LLONG_MIN) id_trap("division overflow");
    return a / b;
}
static long long id_smod(long long a, long long b) {
    if (b == 0) id_trap("remainder by zero");
    if (b == -1) return 0;              /* would overflow; the answer is 0 */
    return a % b;
}
/* The same two checks for `int`. They used to be word-only, on the grounds
   that trapping was a new behaviour and `int` division should stay exactly as
   it was -- but "exactly as it was" meant a SIGFPE and a core dump with no
   message, while the identical mistake on a `word` printed one line and
   exited 1. Two spellings of one bug do not deserve two failure modes, and
   gcc folds the check away whenever the divisor is a nonzero constant. */
static int id_idiv(int a, int b) {
    if (b == 0) id_trap("division by zero");
    if (b == -1 && a == INT_MIN) id_trap("division overflow");
    return a / b;
}
static int id_imod(int a, int b) {
    if (b == 0) id_trap("remainder by zero");
    if (b == -1) return 0;              /* would overflow; the answer is 0 */
    return a % b;
}
static long long id_shl(long long a, long long n) {
    if (n < 0) id_trap("shift by a negative amount");
    if (n >= 64) return 0;
    return (long long)((unsigned long long)a << n);
}
static long long id_sar(long long a, long long n) {   /* arithmetic: `>>` */
    if (n < 0) id_trap("shift by a negative amount");
    if (n >= 64) return a < 0 ? -1 : 0;
    return a >> n;
}
static long long id_ushr(long long a, long long n) {  /* logical: `ushr` */
    if (n < 0) id_trap("shift by a negative amount");
    if (n >= 64) return 0;
    return (long long)((unsigned long long)a >> n);
}
static long long id_udiv(long long a, long long b) {
    if (b == 0) id_trap("division by zero");
    return (long long)((unsigned long long)a / (unsigned long long)b);
}
static long long id_umod(long long a, long long b) {
    if (b == 0) id_trap("remainder by zero");
    return (long long)((unsigned long long)a % (unsigned long long)b);
}
static long long id_ult(long long a, long long b) {
    return (unsigned long long)a < (unsigned long long)b;
}

/* ---- the flat store -----------------------------------------------------
   One flat, byte-addressed memory. An address is an ordinary word, so
   structs become offsets, arrays become strides, and taking the address of
   something is arithmetic -- none of which the language needs syntax for.

   Address 0 is never handed out, so it can mean "null" the way it does
   everywhere else. Every access is bounds-checked against the high-water
   mark: the class of mistake that silently corrupts memory in C is a clean
   abort here, which is the entire reason the store is a primitive rather
   than a library. The store grows on demand and is freed at exit with the
   rest of the arena. */
static unsigned char* id_store = NULL;
static long long id_store_used = 1;    /* 0 is reserved for null */
static long long id_store_cap = 0;

static void id_store_grow(long long need) {
    long long cap = id_store_cap ? id_store_cap : 65536;
    while (cap < need) {
        if (cap > (long long)1 << 44) id_trap("store too large");
        cap *= 2;
    }
    id_store = (unsigned char*)id_realloc(id_store, (size_t)cap);
    memset(id_store + id_store_cap, 0, (size_t)(cap - id_store_cap));
    id_store_cap = cap;
}
static long long id_mem_alloc(long long n) {
    if (n < 0) id_trap("negative allocation size");
    /* 8-align every allocation so a 64-bit field is never split awkwardly */
    long long base = (id_store_used + 7) & ~(long long)7;
    long long end = base + n;
    if (end < base) id_trap("allocation size overflow");
    if (end > id_store_cap) id_store_grow(end);
    id_store_used = end;
    return base;
}
static long long id_mem_size(void) { return id_store_used; }

/* Every load and store funnels through this one check. */
static unsigned char* id_at(long long addr, long long width) {
    if (addr <= 0 || addr + width > id_store_used) {
        fprintf(stderr, "id: store address %lld out of range (size %lld)\n",
                addr, id_store_used);
        exit(1);
    }
    return id_store + addr;
}
/* Little-endian, byte at a time: the same bytes on every host, and no
   alignment requirement -- C code casts pointers to odd addresses freely. */
static long long id_peek_n(long long addr, int width) {
    unsigned char* p = id_at(addr, width);
    unsigned long long v = 0;
    for (int i = width - 1; i >= 0; i--) v = (v << 8) | p[i];
    return (long long)v;
}
static void id_poke_n(long long addr, long long value, int width) {
    unsigned char* p = id_at(addr, width);
    unsigned long long v = (unsigned long long)value;
    for (int i = 0; i < width; i++) { p[i] = (unsigned char)(v & 0xff); v >>= 8; }
}
static long long id_peek8(long long a)  { return id_peek_n(a, 1); }
static long long id_peek16(long long a) { return id_peek_n(a, 2); }
static long long id_peek32(long long a) { return id_peek_n(a, 4); }
static long long id_peek64(long long a) { return id_peek_n(a, 8); }
static void id_poke8(long long a, long long v)  { id_poke_n(a, v, 1); }
static void id_poke16(long long a, long long v) { id_poke_n(a, v, 2); }
static void id_poke32(long long a, long long v) { id_poke_n(a, v, 4); }
static void id_poke64(long long a, long long v) { id_poke_n(a, v, 8); }

/* Bridges between the store and id's own strings, so a program working in
   the store can still print. */
static char* id_str_of_mem(long long addr, long long n) {
    if (n < 0) id_trap("negative length");
    unsigned char* p = id_at(addr, n);
    char* r = (char*)id_alloc((size_t)n + 1);
    memcpy(r, p, (size_t)n);
    r[n] = '\0';
    return r;
}
static long long id_mem_of_str(const char* s) {
    size_t n = strlen(s);
    long long a = id_mem_alloc((long long)n + 1);
    memcpy(id_store + a, s, n + 1);
    return a;
}
static char* id_str_of_float(double x) {
    char* r = (char*)id_alloc(64); snprintf(r, 64, "%g", x); return r;
}
static void id_print(const char* s) { puts(s); }
static char* id_input(void) {
    /* read one line from stdin, drop the trailing newline; "" on EOF */
    char buf[1024];
    if (!fgets(buf, sizeof(buf), stdin)) {
        char* e = (char*)id_alloc(1); e[0] = '\0'; return e;
    }
    size_t n = strlen(buf);
    if (n > 0 && buf[n - 1] == '\n') { buf[--n] = '\0'; }
    char* r = (char*)id_alloc(n + 1); memcpy(r, buf, n + 1); return r;
}
static char* id_read_all(void) {
    /* slurp all of stdin into one string (grows as needed) */
    size_t cap = 4096, n = 0;
    char* r = (char*)id_alloc(cap);
    for (;;) {
        if (n + 1 >= cap) {
            if (cap > SIZE_MAX / 2) {
                fprintf(stderr, "id: allocation size overflow (read_all)\n");
                exit(1);
            }
            cap *= 2;
            r = (char*)id_realloc(r, cap);
        }
        size_t got = fread(r + n, 1, cap - n - 1, stdin);
        n += got;
        if (got == 0) break;
    }
    r[n] = '\0';
    return r;
}
static int id_len(const char* s) { return (int)id_slen(s); }
/* charat's bounds check used to be a strlen per character, which makes walking
   a string O(n^2) -- and walking a string with charat is how every id program
   reads text, because there is no substr and no file I/O. Lexing a 128 KB
   source took 378 ms; with the length of the last string remembered it takes
   12 ms, and the answer is the same.
   The memo is keyed on the pointer, which is sound because an id string is
   immutable and its block is never released before exit. The one place a block
   can be released early is id_realloc (list growth), whose freed address could
   later be handed to a new string -- so it clears the memo. */
static int id_charat(const char* s, int i) {
    if (i < 0) return -1;
    if ((size_t)i >= id_slen(s)) return -1;        /* out of range -> -1 */
    return (unsigned char)s[i];
}
static char* id_chr(int code) {
    char* r = (char*)id_alloc(2);
    r[0] = (char)code; r[1] = '\0';
    return r;
}

/* real-time terminal I/O: write without a newline, flush, poll a single key
   without blocking (raw mode is entered lazily and restored at exit), and
   sleep. Together these let id drive an animated full-screen frame loop. */
static void id_put(const char* s) { fputs(s, stdout); }
static void id_flush(void) { fflush(stdout); }
static struct termios id_saved_termios;
static int id_raw_active = 0;
static void id_term_restore(void) {
    if (id_raw_active) {
        tcsetattr(STDIN_FILENO, TCSANOW, &id_saved_termios);
        id_raw_active = 0;
    }
}
static void id_term_raw(void) {
    struct termios t;
    if (id_raw_active) return;
    if (tcgetattr(STDIN_FILENO, &id_saved_termios) != 0) return;
    t = id_saved_termios;
    t.c_lflag &= ~(tcflag_t)(ICANON | ECHO);
    t.c_cc[VMIN] = 0; t.c_cc[VTIME] = 0;   /* read() returns at once, 0 on no key */
    tcsetattr(STDIN_FILENO, TCSANOW, &t);
    id_raw_active = 1;
    atexit(id_term_restore);
}
static int id_getkey(void) {
    unsigned char c;
    id_term_raw();
    if (read(STDIN_FILENO, &c, 1) == 1) return (int)c;
    return -1;   /* no key available this poll */
}
static void id_sleep_ms(int ms) {
    struct timespec ts;
    if (ms < 0) ms = 0;
    ts.tv_sec = ms / 1000;
    ts.tv_nsec = (long)(ms % 1000) * 1000000L;
    nanosleep(&ts, NULL);
}
static int id_ticks(void) {   /* monotonic milliseconds, for timing and seeding */
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (int)(ts.tv_sec * 1000 + ts.tv_nsec / 1000000);
}

/* forward declarations */
void id_lset(IdList* xs, int i, int v);
int id_is_space_at(char* src, int i);
int id_is_digit_at(char* src, int i);
int id_is_alpha_at(char* src, int i);
int id_is_alnum_at(char* src, int i);
int id_is_hex_at(char* src, int i);
int id_is_bin_at(char* src, int i);
int id_is_space(int c);
int id_is_digit(int c);
int id_is_alpha(int c);
int id_is_alnum(int c);
int id_is_kw(char* w);
char* id_kindof(char* w);
int id_scan_one(char* src, int i);
int id_scan_word(char* src, int i);
int id_scan_token(char* src, int i);
int id_scan_numop(char* src, int i);
int id_scan_strop(char* src, int i);
int id_skip_comment(char* src, int i);
int id_scan_block(char* src, int i);
int id_block_tok(char* src, int i);
int id_skip_block(char* src, int i);
void id_bump_line(void);
int id_scan_decop(char* src, int i);
int id_scan_hashop(char* src, int i);
int id_scan_hash(char* src, int i);
int id_is_bin(int c);
int id_bin_start(char* src, int i);
int id_bin_end(char* src, int i);
int id_scan_binop(char* src, int i);
int id_scan_bin(char* src, int i);
long long id_bin_val(char* src, int i, int e);
int id_num_end(char* src, int i, int e);
char* id_numkind(int e, int fe);
int id_digit_run_end(char* src, int i);
int id_has_frac(char* src, int e);
int id_is_hex(int c);
int id_hex_digit(int c);
int id_hex_alpha(int c);
int id_hex_start(char* src, int i);
int id_hex_end(char* src, int i);
long long id_hex_val(char* src, int i, int e);
int id_scan_hex(char* src, int i);
char* id_udec(long long v);
char* id_pad10(char* s);
void id_print_uint(long long v);
void id_lex_all(void);
int id_main(int argc, IdList* argv);
int id_eat_space(char* src, int i);
void id_lex(char* src);
char* id_two_at(char* src, int i);
char* id_one_at(char* src, int i);
void id_scan_op_out(char* src, int i, char* two);
int id_is_two_op(char* two);
int id_oplen(char* src, int i);
int id_scan_op(char* src, int i);
void id_scan_ident_out(char* ident);
void id_scan_num_out(char* src, int i, int e, int fe);
void id_scan_str_out(char* src, int i, int e);
void id_scan_hash_out(char* src, int i, int e);
int id_scan_ident(char* src, int i);
int id_scan_number(char* src, int i);
int id_scan_string(char* src, int i);
int id_str_end(char* src, int i);
int id_adv_str(char* src, int i);
char* id_slice_str(char* src, int a, int b);

/* exported variables */
IdList* rnd_st;  /* exported by rnd_init() */
IdList* fx_sintab;  /* exported by fx_trig_init() */
IdList* err_n;  /* exported by err_init() */
IdList* err_fs;  /* exported by err_keep_init() */
IdList* err_ls;  /* exported by err_keep_init() */
IdList* err_ms;  /* exported by err_keep_init2() */
IdList* lexline;  /* exported by main() */

void id_lset(IdList* xs, int i, int v) {
    id_list_set(xs, i, (long long)(v));
    return;
}

int id_is_space_at(char* src, int i) {
    int c;
    int ok;
    c = id_charat(src, i);
    ok = id_is_space(c);
    return ok;
}

int id_is_digit_at(char* src, int i) {
    int c;
    int ok;
    c = id_charat(src, i);
    ok = id_is_digit(c);
    return ok;
}

int id_is_alpha_at(char* src, int i) {
    int c;
    int ok;
    c = id_charat(src, i);
    ok = id_is_alpha(c);
    return ok;
}

int id_is_alnum_at(char* src, int i) {
    int c;
    int ok;
    c = id_charat(src, i);
    ok = id_is_alnum(c);
    return ok;
}

int id_is_hex_at(char* src, int i) {
    int c;
    int ok;
    c = id_charat(src, i);
    ok = id_is_hex(c);
    return ok;
}

int id_is_bin_at(char* src, int i) {
    int c;
    int ok;
    c = id_charat(src, i);
    ok = id_is_bin(c);
    return ok;
}

int id_is_space(int c) {
    int ok;
    ok = 0;
    if (((((c == 32) || (c == 9)) || (c == 10)) || (c == 13))) {
        ok = 1;
    }
    return ok;
}

int id_is_digit(int c) {
    int ok;
    ok = 0;
    if (((c >= 48) && (c <= 57))) {
        ok = 1;
    }
    return ok;
}

int id_is_alpha(int c) {
    int ok;
    ok = 0;
    if (((((c >= 65) && (c <= 90)) || ((c >= 97) && (c <= 122))) || (c == 95))) {
        ok = 1;
    }
    return ok;
}

int id_is_alnum(int c) {
    int ok;
    ok = 0;
    if ((id_is_alpha(c) || id_is_digit(c))) {
        ok = 1;
    }
    return ok;
}

int id_is_kw(char* w) {
    int ok;
    ok = 0;
    if (((((((((((((strcmp(w, "int") == 0) || (strcmp(w, "float") == 0)) || (strcmp(w, "string") == 0)) || (strcmp(w, "void") == 0)) || (strcmp(w, "if") == 0)) || (strcmp(w, "else") == 0)) || (strcmp(w, "while") == 0)) || (strcmp(w, "return") == 0)) || (strcmp(w, "export") == 0)) || (strcmp(w, "import") == 0)) || (strcmp(w, "word") == 0)) || (strcmp(w, "asm") == 0))) {
        ok = 1;
    }
    return ok;
}

char* id_kindof(char* w) {
    char* kind;
    kind = "ident";
    if (id_is_kw(w)) {
        kind = "kw";
    }
    return kind;
}

int id_scan_one(char* src, int i) {
    int ni;
    ni = 0;
    if (id_is_space_at(src, i)) {
        ni = id_eat_space(src, i);
    } else {
        ni = id_scan_word(src, i);
    }
    return ni;
}

int id_scan_word(char* src, int i) {
    int ni;
    ni = 0;
    if (((id_charat(src, i) == 47) && (id_charat(src, (i + 1)) == 47))) {
        ni = id_skip_comment(src, i);
    } else {
        ni = id_scan_block(src, i);
    }
    return ni;
}

int id_scan_token(char* src, int i) {
    int ni;
    ni = 0;
    if (id_is_alpha_at(src, i)) {
        ni = id_scan_ident(src, i);
    } else {
        ni = id_scan_numop(src, i);
    }
    return ni;
}

int id_scan_numop(char* src, int i) {
    int ni;
    ni = 0;
    if (id_hex_start(src, i)) {
        ni = id_scan_hex(src, i);
    } else {
        ni = id_scan_binop(src, i);
    }
    return ni;
}

int id_scan_strop(char* src, int i) {
    int ni;
    ni = 0;
    if ((id_charat(src, i) == 34)) {
        ni = id_scan_string(src, (i + 1));
    } else {
        ni = id_scan_op(src, i);
    }
    return ni;
}

int id_skip_comment(char* src, int i) {
    while (((id_charat(src, i) != 10) && (id_charat(src, i) != (-1)))) {
        i = (i + 1);
    }
    return i;
}

int id_scan_block(char* src, int i) {
    int ni;
    ni = 0;
    if (((id_charat(src, i) == 47) && (id_charat(src, (i + 1)) == 42))) {
        ni = id_block_tok(src, i);
    } else {
        ni = id_scan_hashop(src, i);
    }
    return ni;
}

int id_block_tok(char* src, int i) {
    int e;
    id_print("op /*");
    e = id_skip_block(src, (i + 2));
    return e;
}

int id_skip_block(char* src, int i) {
    int ret_i;
    while (((id_charat(src, i) != (-1)) && ((id_charat(src, i) != 42) || (id_charat(src, (i + 1)) != 47)))) {
        i = id_eat_space(src, i);
    }
    ret_i = (i + 2);
    return ret_i;
}

void id_bump_line(void) {
    id_lset(lexline, 0, ((int)(id_list_get(lexline, 0)) + 1));
    id_print(id_concat("line ", id_str_of_int((int)(id_list_get(lexline, 0)))));
    return;
}

int id_scan_decop(char* src, int i) {
    int ni;
    ni = 0;
    if (id_is_digit_at(src, i)) {
        ni = id_scan_number(src, i);
    } else {
        ni = id_scan_strop(src, i);
    }
    return ni;
}

int id_scan_hashop(char* src, int i) {
    int ni;
    ni = 0;
    if ((id_charat(src, i) == 35)) {
        ni = id_scan_hash(src, i);
    } else {
        ni = id_scan_token(src, i);
    }
    return ni;
}

int id_scan_hash(char* src, int i) {
    int e;
    e = id_skip_comment(src, i);
    id_scan_hash_out(src, i, e);
    id_lset(lexline, 0, 0);
    return e;
}

int id_is_bin(int c) {
    int ok;
    ok = 0;
    if (((c == 48) || (c == 49))) {
        ok = 1;
    }
    return ok;
}

int id_bin_start(char* src, int i) {
    int ok;
    ok = 0;
    if ((((id_charat(src, i) == 48) && ((id_charat(src, (i + 1)) == 98) || (id_charat(src, (i + 1)) == 66))) && id_is_bin_at(src, (i + 2)))) {
        ok = 1;
    }
    return ok;
}

int id_bin_end(char* src, int i) {
    while (id_is_bin_at(src, i)) {
        i = (i + 1);
    }
    return i;
}

int id_scan_binop(char* src, int i) {
    int ni;
    ni = 0;
    if (id_bin_start(src, i)) {
        ni = id_scan_bin(src, i);
    } else {
        ni = id_scan_decop(src, i);
    }
    return ni;
}

int id_scan_bin(char* src, int i) {
    int e;
    long long v;
    e = id_bin_end(src, (i + 2));
    v = id_bin_val(src, (i + 2), e);
    id_print_uint(v);
    return e;
}

long long id_bin_val(char* src, int i, int e) {
    long long v;
    v = 0;
    while ((i < e)) {
        v = (((v * 2) + id_charat(src, i)) - 48);
        i = (i + 1);
    }
    return v;
}

int id_num_end(char* src, int i, int e) {
    int fe;
    fe = e;
    if (id_has_frac(src, e)) {
        fe = id_digit_run_end(src, (e + 1));
    }
    return fe;
}

char* id_numkind(int e, int fe) {
    char* kind;
    kind = "int";
    if ((fe > e)) {
        kind = "float";
    }
    return kind;
}

int id_digit_run_end(char* src, int i) {
    while (id_is_digit_at(src, i)) {
        i = (i + 1);
    }
    return i;
}

int id_has_frac(char* src, int e) {
    int ok;
    ok = 0;
    if (((id_charat(src, e) == 46) && id_is_digit_at(src, (e + 1)))) {
        ok = 1;
    }
    return ok;
}

int id_is_hex(int c) {
    int ok;
    ok = 0;
    if (((id_is_digit(c) || ((c >= 97) && (c <= 102))) || ((c >= 65) && (c <= 70)))) {
        ok = 1;
    }
    return ok;
}

int id_hex_digit(int c) {
    int n;
    n = (c - 48);
    if ((c >= 65)) {
        n = id_hex_alpha(c);
    }
    return n;
}

int id_hex_alpha(int c) {
    int n;
    n = (c - 55);
    if ((c >= 97)) {
        n = (c - 87);
    }
    return n;
}

int id_hex_start(char* src, int i) {
    int ok;
    ok = 0;
    if ((((id_charat(src, i) == 48) && ((id_charat(src, (i + 1)) == 120) || (id_charat(src, (i + 1)) == 88))) && id_is_hex_at(src, (i + 2)))) {
        ok = 1;
    }
    return ok;
}

int id_hex_end(char* src, int i) {
    while (id_is_hex_at(src, i)) {
        i = (i + 1);
    }
    return i;
}

long long id_hex_val(char* src, int i, int e) {
    long long v;
    int charat_v;
    v = 0;
    while ((i < e)) {
        charat_v = id_charat(src, i);
        v = ((v * 16) + id_hex_digit(charat_v));
        i = (i + 1);
    }
    return v;
}

int id_scan_hex(char* src, int i) {
    int e;
    long long v;
    e = id_hex_end(src, (i + 2));
    v = id_hex_val(src, (i + 2), e);
    id_print_uint(v);
    return e;
}

char* id_udec(long long v) {
    long long hi;
    char* s;
    long long umod_v;
    hi = id_udiv((long long)(v), (long long)(10000000000LL));
    s = id_concat("", id_str_of_word(v));
    if ((hi != 0)) {
        umod_v = id_umod((long long)(v), (long long)(10000000000LL));
        s = id_concat(id_concat("", id_str_of_word(hi)), id_pad10(id_concat("", id_str_of_word(umod_v))));
    }
    return s;
}

char* id_pad10(char* s) {
    while ((id_len(s) < 10)) {
        s = id_concat("0", s);
    }
    return s;
}

void id_print_uint(long long v) {
    char* text;
    text = id_udec(v);
    id_print(id_concat("int ", text));
    return;
}

void id_lex_all(void) {
    char* src;
    src = id_read_all();
    id_lex(src);
    return;
}

int id_main(int argc, IdList* argv) {
    lexline = id_list_lit(1, (long long)(1));
    id_lex_all();
    id_print("eof");
    return 0;
}

int id_eat_space(char* src, int i) {
    int ret_i;
    if ((id_charat(src, i) == 10)) {
        id_bump_line();
    }
    ret_i = (i + 1);
    return ret_i;
}

void id_lex(char* src) {
    int n;
    int i;
    n = id_len(src);
    i = 0;
    while ((i < n)) {
        i = id_scan_one(src, i);
    }
    return;
}

char* id_two_at(char* src, int i) {
    int c1;
    int c2;
    char* two;
    c1 = id_charat(src, i);
    c2 = id_charat(src, (i + 1));
    two = id_concat(id_chr(c1), id_chr(c2));
    return two;
}

char* id_one_at(char* src, int i) {
    int c;
    char* one;
    c = id_charat(src, i);
    one = id_chr(c);
    return one;
}

void id_scan_op_out(char* src, int i, char* two) {
    char* one;
    one = id_one_at(src, i);
    if (id_is_two_op(two)) {
        id_print(id_concat("op ", two));
    } else {
        id_print(id_concat("op ", one));
    }
    return;
}

int id_is_two_op(char* two) {
    int ok;
    ok = 0;
    if (((((((((strcmp(two, "==") == 0) || (strcmp(two, "!=") == 0)) || (strcmp(two, "<=") == 0)) || (strcmp(two, ">=") == 0)) || (strcmp(two, "&&") == 0)) || (strcmp(two, "||") == 0)) || (strcmp(two, "<<") == 0)) || (strcmp(two, ">>") == 0))) {
        ok = 1;
    }
    return ok;
}

int id_oplen(char* src, int i) {
    int n;
    char* two;
    n = 1;
    two = id_two_at(src, i);
    if (id_is_two_op(two)) {
        n = 2;
    }
    return n;
}

int id_scan_op(char* src, int i) {
    char* two;
    int ret_i;
    two = id_two_at(src, i);
    id_scan_op_out(src, i, two);
    ret_i = (i + id_oplen(src, i));
    return ret_i;
}

void id_scan_ident_out(char* ident) {
    char* kind;
    kind = id_kindof(ident);
    id_print(id_concat(id_concat(kind, " "), ident));
    return;
}

void id_scan_num_out(char* src, int i, int e, int fe) {
    char* kind;
    char* text;
    kind = id_numkind(e, fe);
    text = id_slice_str(src, i, fe);
    id_print(id_concat(id_concat(kind, " "), text));
    return;
}

void id_scan_str_out(char* src, int i, int e) {
    char* q;
    char* text;
    q = id_chr(34);
    text = id_slice_str(src, i, e);
    id_print(id_concat(id_concat(id_concat("str ", q), text), q));
    return;
}

void id_scan_hash_out(char* src, int i, int e) {
    char* text;
    text = id_slice_str(src, (i + 1), e);
    id_print(text);
    return;
}

int id_scan_ident(char* src, int i) {
    char* ident;
    int charat_v;
    ident = "";
    while (id_is_alnum_at(src, i)) {
        charat_v = id_charat(src, i);
        ident = id_concat(ident, id_chr(charat_v));
        i = (i + 1);
    }
    id_scan_ident_out(ident);
    return i;
}

int id_scan_number(char* src, int i) {
    int e;
    int fe;
    e = id_digit_run_end(src, i);
    fe = id_num_end(src, i, e);
    id_scan_num_out(src, i, e, fe);
    return fe;
}

int id_scan_string(char* src, int i) {
    int e;
    int ret_i;
    e = id_str_end(src, i);
    id_scan_str_out(src, i, e);
    ret_i = (e + 1);
    return ret_i;
}

int id_str_end(char* src, int i) {
    while (((id_charat(src, i) != 34) && (id_charat(src, i) != (-1)))) {
        i = id_adv_str(src, i);
    }
    return i;
}

int id_adv_str(char* src, int i) {
    int n;
    n = (i + 1);
    if ((id_charat(src, i) == 92)) {
        n = (i + 2);
    }
    return n;
}

char* id_slice_str(char* src, int a, int b) {
    char* out;
    int charat_v;
    out = "";
    while ((a < b)) {
        charat_v = id_charat(src, a);
        out = id_concat(out, id_chr(charat_v));
        a = (a + 1);
    }
    return out;
}

int main(int argc, char** argv) { (void)argc; (void)argv;
    IdList* id_args = id_list_new();
    for (int i = 0; i < argc; i++)
        id_list_push(id_args, (long long)(intptr_t)argv[i]);
    return id_main(argc, id_args); }

