#!/usr/bin/env python3
"""Generate the id-side copies of things derived from idc.py's RUNTIME.

Two files, both from the same source of truth:

  back/tgt/c/runtime/runtime.id       emit_runtime(), the prelude verbatim
  back/tgt/c/runtime/reserved.gen.id  resv_names(), the helper names it
                                        defines, which an id program may
                                        therefore not name a function after

The id-written compiler must emit the exact same C as idc.py, including the
runtime prelude. Rather than hand-copy that ~90-line block (and risk drift),
this regenerates an id function `emit_runtime()` that prints it verbatim.

id string literals are passed through to C unchanged, so escaping the runtime
for an id string literal is exactly C-string escaping. Run after changing
idc.py's RUNTIME:  python3 tools/gen_runtime_id.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)
import idc  # noqa: E402

OUT = os.path.join(ROOT, "compiler", "parse",
                   "back", "tgt", "c", "runtime", "runtime.id")
RESV_OUT = os.path.join(ROOT, "compiler", "parse",
                        "back", "tgt", "c", "runtime", "reserved.gen.id")
CRT_OUT = os.path.join(ROOT, "compiler", "parse",
                       "back", "tgt", "c", "runtime", "extern.gen.id")


def escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def main():
    # idc.py joins RUNTIME with the rest using "\n"; RUNTIME already ends with a
    # newline, so the printed block must end at the final "}" (the caller adds
    # the blank line). Drop exactly one trailing newline.
    runtime = idc.RUNTIME
    if runtime.endswith("\n"):
        runtime = runtime[:-1]

    body = escape(runtime)
    with open(OUT, "w") as f:
        f.write(
            "// GENERATED by tools/gen_runtime_id.py from idc.py's RUNTIME -- do\n"
            "// not edit. Prints the C runtime prelude verbatim so the id-written\n"
            "// compiler emits byte-identical C to idc.py.\n"
            "\n"
            "emit_runtime() {\n"
            f'  print("{body}");\n'
            "} return void;\n"
        )
    print(f"wrote {OUT} ({len(runtime)} bytes of runtime)")
    write_extern(runtime)
    write_reserved()


def write_extern(runtime):
    """The same prelude with external linkage, for the LLVM target.

    The C target splices the runtime into one translation unit and marks every
    helper `static`; the LLVM target compiles it as a translation unit of its
    own that a separate .ll calls into, so the same helpers have to be visible.
    Generated rather than stripped at run time because `id` builds a string by
    concatenation, and rewriting sixteen kilobytes that way is quadratic.

    This file exists only while the LLVM target links a C runtime. The runtime
    written in `id` replaces it -- see docs/LLVM.md.
    """
    body = escape(runtime.replace("\nstatic ", "\n"))
    with open(CRT_OUT, "w") as f:
        f.write(
            "// GENERATED by tools/gen_runtime_id.py from idc.py's RUNTIME -- do\n"
            "// not edit. The C runtime with external linkage, which is what the\n"
            "// LLVM target links against: it compiles the runtime as its own\n"
            "// translation unit rather than splicing it into the program.\n"
            "\n"
            "emit_crt() {\n"
            f'  print("{body}");\n'
            "} return void;\n"
        )
    print(f"wrote {CRT_OUT} (external-linkage runtime)")


def write_reserved():
    """The runtime helper names, as an id function returning a string[].

    Derived from idc.py's RUNTIME_HELPERS, which is itself derived from
    RUNTIME, so adding a helper to the prelude reserves its name in both
    compilers in the same commit. tests/stdlib.sh asserts the two agree.
    """
    names = sorted(idc.RUNTIME_HELPERS)
    items = ", ".join(f'"{n}"' for n in names)
    os.makedirs(os.path.dirname(RESV_OUT), exist_ok=True)
    with open(RESV_OUT, "w") as f:
        f.write(
            "// GENERATED by tools/gen_runtime_id.py from idc.py's RUNTIME --\n"
            "// do not edit. The C functions the runtime prelude defines.\n"
            "//\n"
            "// Every id function is emitted as id_<name>, so an id function\n"
            "// named after one of these collides with the runtime in C. Left\n"
            "// unchecked that surfaced as a cc error attributed to nobody --\n"
            "// and bin/idc reported a user's typo as a bug in the compiler.\n"
            "\n"
            "// The list is built into a local rather than returned directly:\n"
            "// `return string[] [...]` does not parse -- the `[` after a type\n"
            "// reads as an index -- in either compiler.\n"
            "resv_names() {\n"
            f"  string[] rnames = [{items}];\n"
            "} return string[] rnames;\n"
        )
    print(f"wrote {RESV_OUT} ({len(names)} reserved names)")


if __name__ == "__main__":
    main()
