#!/usr/bin/env python3
"""Generate demos/idc_in_id_parse/runtime.id from idc.py's RUNTIME string.

The id-written compiler must emit the exact same C as idc.py, including the
runtime prelude. Rather than hand-copy that ~90-line block (and risk drift),
this regenerates an id function `emit_runtime()` that prints it verbatim.

id string literals are passed through to C unchanged, so escaping the runtime
for an id string literal is exactly C-string escaping. Run after changing
idc.py's RUNTIME:  python3 tools/gen_runtime_id.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)
import idc  # noqa: E402

OUT = os.path.join(ROOT, "demos", "idc_in_id_parse", "runtime.id")


def escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def main():
    # idc.py joins RUNTIME with the rest using "\n"; RUNTIME already ends with a
    # newline, so the printed block must end at the final "}" (the caller adds
    # the blank line). Drop exactly one trailing newline.
    runtime = idc.RUNTIME
    if runtime.endswith("\n"):
        runtime = runtime[:-1]

    body = escape(runtime)
    with open(OUT, "w") as f:
        f.write(
            "// GENERATED by tools/gen_runtime_id.py from idc.py's RUNTIME -- do\n"
            "// not edit. Prints the C runtime prelude verbatim so the id-written\n"
            "// compiler emits byte-identical C to idc.py.\n"
            "\n"
            "emit_runtime() {\n"
            f'  print("{body}");\n'
            "} return void;\n"
        )
    print(f"wrote {OUT} ({len(runtime)} bytes of runtime)")


if __name__ == "__main__":
    main()
