#!/usr/bin/env bash
# Generate the self-hosted compiler's map: every function, where it lives, and
# what it is for.
#
#   tools/mapgen.sh            # rewrite compiler/parse/MAP.md
#   tools/mapgen.sh --check    # fail if that file is out of date
#
# Why this exists: the compiler is 258 files and 9 directories deep, because
# the rule of 3 makes a program that size into a deep tree. Every file is now
# named after what it does -- 212 of them were not, and finding anything meant
# already knowing a symbol to grep for, which is why new work kept landing in
# idc.py instead. The names carry most of the weight now; this index carries
# the rest, for when you know a function's name but not where it lives.
#
# It is deliberately NOT written in Python. The bash driver layer has to exist
# anyway (id cannot walk a directory tree, which is the whole reason bin/idc
# is a shell script); Python is the dependency being retired, so tooling that
# can live in the layer that must exist should live there.
set -u
cd "$(dirname "$0")/.."

SRC=compiler/parse
LEX=compiler/lex
OUT=$SRC/MAP.md

phase_of() {
    case "$1" in
        $LEX/*)     echo "lex" ;;
        $SRC/front/*) echo "front" ;;
        $SRC/mid/*)   echo "mid" ;;
        $SRC/back/*)  echo "back" ;;
        *)            echo "other" ;;
    esac
}

# For each .id file: every function definition, plus a one-line description.
# A definition is a line starting at column 0 with `name(`; a comment line
# starts with `//`.
#
# A function with a comment block directly above it uses that block's first
# line. One without falls back to the FILE's opening comment -- because the
# house style here is a header comment and then up to three functions, so
# taking only adjacent comments described 212 of 737 functions. Inheriting the
# header takes it to 710, and a file header in this tree is a good description
# of everything in the file, since the file holds at most three closely
# related functions.
extract() {
    find "$LEX" "$SRC" -name '*.id' | LC_ALL=C sort | xargs awk '
        FNR == 1 { header = ""; inheader = 1; own = ""; incomment = 0 }
        /^\/\// {
            line = $0; sub(/^\/\/ ?/, "", line)
            if (inheader && header == "") header = line
            if (!incomment) { own = line; incomment = 1 }
            next
        }
        /^[a-z_][a-z_0-9]*\(/ {
            name = $0; sub(/\(.*/, "", name)
            printf "%s\t%s\t%s\n", name, FILENAME, (incomment ? own : header)
            incomment = 0; own = ""; inheader = 0
            next
        }
        { incomment = 0; own = ""; if ($0 != "") inheader = 0 }
    '
}

generate() {
    local total
    total=$(extract | wc -l)
    cat <<EOF
# Where everything is

GENERATED by \`tools/mapgen.sh\` -- do not edit. Regenerate after adding or
moving a function; \`tests/run.sh\` fails if this file is out of date.

$total functions. The compiler is a pipeline, and this file is grouped the way
it runs: **lex** turns text into tokens, **front** turns tokens into an AST,
**mid** checks the AST and answers questions about types, **back** turns it
into C. Nothing in \`front\` or \`mid\` may emit C -- see
[\`../../docs/BACKENDS.md\`](../../docs/BACKENDS.md).

To add a language feature, start here, not in \`idc.py\`. \`idc.py\` is stage 0
of the bootstrap: it only has to compile *this tree's own source*, so it needs
a new construct only once this compiler uses that construct on itself.
EOF
    for phase in lex front mid back other; do
        local rows
        rows=$(extract | while IFS=$'\t' read -r name file why; do
                   [ "$(phase_of "$file")" = "$phase" ] && printf '| `%s` | `%s` | %s |\n' \
                       "$name" "${file#demos/}" "$why"
               done)
        [ -n "$rows" ] || continue
        echo
        case $phase in
            lex)   echo "## lex -- source text to tokens" ;;
            front) echo "## front -- tokens to an AST" ;;
            mid)   echo "## mid -- checks, types, symbol tables" ;;
            back)  echo "## back -- the C target" ;;
            other) echo "## other" ;;
        esac
        echo
        echo "| function | file | what |"
        echo "| --- | --- | --- |"
        printf '%s\n' "$rows"
    done
}

if [ "${1-}" = "--check" ]; then
    if generate | diff -q - "$OUT" >/dev/null 2>&1; then
        echo "mapgen: $OUT is current"
        exit 0
    fi
    echo "mapgen: $OUT is out of date -- run tools/mapgen.sh" >&2
    exit 1
fi

generate > "$OUT"
echo "mapgen: wrote $OUT ($(extract | wc -l) functions)"
