#!/usr/bin/env python3
"""Turn a PSF console font into `id` source: kernel/prog/sys/gfx/font/rom*.id.

The kernel needs a bitmap font and `id` has no way to hold one. A string cannot
contain a NUL (docs/SPEC.md 4) and a font is mostly zero rows, so the glyphs
travel as hexadecimal text and are decoded into an int[] at boot. That is the
language's cost for having no byte-array literal, and it is written down here
rather than discovered in the kernel.

Output is checked in, so a build needs neither this script nor a font package.
"""
import gzip, os, struct, sys, glob

FIRST, LAST = 32, 126          # printable ASCII; the console needs no more yet
HEIGHT = 16
PER_FN = 24                    # glyphs per generated function, to keep each
                               # string literal short -- the lexer builds a
                               # string with `+` and that is quadratic

def load_psf(path):
    d = gzip.open(path, "rb").read() if path.endswith(".gz") else open(path, "rb").read()
    if d[:4] == b"\x72\xb5\x4a\x86":                      # PSF2
        ver, hdr, flags, n, csz, h, w = struct.unpack("<7I", d[4:32])
        return d[hdr:], n, csz, h, w
    if d[:2] == b"\x36\x04":                              # PSF1
        mode, csz = d[2], d[3]
        n = 512 if mode & 1 else 256
        return d[4:], n, csz, csz, 8
    sys.exit(f"{path}: not a PSF font")

def main():
    src = sys.argv[1] if len(sys.argv) > 1 else None
    if not src:
        for pat in ("lat0-16.psfu.gz", "lat2-16.psfu.gz", "Lat2-Terminus16.psfu.gz"):
            hit = glob.glob(f"/nix/store/*/share/consolefonts/{pat}")
            if hit:
                src = hit[0]
                break
    if not src:
        sys.exit("no 8x16 PSF font found; pass one as an argument")

    glyphs, n, csz, h, w = load_psf(src)
    if w != 8 or h != HEIGHT:
        sys.exit(f"{src}: {w}x{h}, wanted 8x{HEIGHT}")

    rows = []
    for c in range(FIRST, LAST + 1):
        g = glyphs[c * csz: c * csz + HEIGHT]
        rows.append("".join(f"{b:02x}" for b in g))

    # rom0 at the top, the rest one level down: three entries per directory,
    # and five files do not fit in one.
    out = "kernel/prog/sys/gfx/font/rom"
    os.makedirs(out + "/more", exist_ok=True)
    chunks = [rows[i:i + PER_FN] for i in range(0, len(rows), PER_FN)]
    names = []
    for i, ch in enumerate(chunks):
        names.append(f"font_rom{i}")

    head = (f"// GENERATED by tools/mkfont.py from {os.path.basename(src)} -- do not\n"
            f"// edit. An 8x{HEIGHT} bitmap font, glyphs {FIRST} to {LAST}, one byte per\n"
            "// row, most significant bit leftmost.\n"
            "//\n"
            "// Hexadecimal text rather than bytes, because `id` has no byte-array\n"
            "// literal and a string cannot hold a NUL -- which a font is mostly made\n"
            "// of. font_init decodes it once at boot.\n"
            "//\n"
            f"// Split across {len(chunks)} functions because the lexer builds a string\n"
            "// literal by concatenation, which is quadratic (docs/TODO.md item 10):\n"
            "// one literal of six thousand characters costs measurably more than\n"
            f"// {len(chunks)} of a few hundred.\n\n")

    for i, ch in enumerate(chunks):
        body = "".join(ch)
        path = f"{out}/rom{i}.id" if i == 0 else f"{out}/more/rom{i}.id"
        with open(path, "w") as f:
            f.write(head if i == 0 else
                    f"// GENERATED by tools/mkfont.py -- do not edit. See rom0.id.\n\n")
            f.write(f"{names[i]}() {{\n}} return string \"{body}\";\n")
        print(f"wrote {path} ({len(body)} hex characters, {len(ch)} glyphs)")

    with open(f"{out}/all.id", "w") as f:
        f.write("// GENERATED by tools/mkfont.py -- do not edit. See rom0.id.\n"
                "//\n"
                "// The whole font, in order. Concatenating the parts is the one place\n"
                "// the quadratic cost is paid, and it is paid once at boot.\n\n"
                "font_rom() {\n} return string " + " + ".join(f"{n}()" for n in names) + ";\n")
    print(f"wrote {out}/all.id")

main()
