#!/usr/bin/env python3
"""Generate kernel/prog/sys/hw/kbd/tab/map/*.id -- scancode set 1 to ASCII.

Two tables of 128 bytes, unshifted and shifted, as hexadecimal text for the
same reason the font is (see tools/mkfont.py): `id` has no byte-array literal,
and a keymap is mostly zeros -- which a string cannot hold.

Zero means "no character": a modifier, a function key, or a code this layout
does not use. The driver treats it as nothing happening rather than as a NUL.
"""
import os

LOW  = {}
HIGH = {}

def row(codes, low, high):
    for c, a, b in zip(codes, low, high):
        LOW[c], HIGH[c] = ord(a), ord(b)

row(range(0x02, 0x0E), "1234567890-=", "!@#$%^&*()_+")
row(range(0x10, 0x1C), "qwertyuiop[]", "QWERTYUIOP{}")
row(range(0x1E, 0x29), "asdfghjkl;'", "ASDFGHJKL:\"")
row([0x29], "`", "~")
row([0x2B], "\\", "|")
row(range(0x2C, 0x36), "zxcvbnm,./", "ZXCVBNM<>?")

for c, v in ((0x01, 27), (0x0E, 8), (0x0F, 9), (0x1C, 10), (0x39, 32),
             (0x37, ord("*")), (0x4A, ord("-")), (0x4E, ord("+"))):
    LOW[c] = HIGH[c] = v

def hexline(tab):
    return "".join(f"{tab.get(i, 0):02x}" for i in range(128))

out = "kernel/prog/sys/hw/kbd/tab/map"
os.makedirs(out, exist_ok=True)

HEAD = ("// GENERATED by tools/mkkeymap.py -- do not edit. Scancode set 1 to\n"
        "// ASCII, 128 entries, two hexadecimal digits each.\n"
        "//\n"
        "// Zero means no character: a modifier, a function key, or a code this\n"
        "// layout does not use. Hexadecimal rather than a string of characters\n"
        "// because a string cannot hold a NUL and this table is mostly zeros --\n"
        "// the same reason the font is hexadecimal (tools/mkfont.py).\n\n")

with open(f"{out}/plain.id", "w") as f:
    f.write(HEAD + f'kb_low() {{\n}} return string "{hexline(LOW)}";\n')
with open(f"{out}/shift.id", "w") as f:
    f.write("// GENERATED by tools/mkkeymap.py -- do not edit. See plain.id.\n\n"
            f'kb_high() {{\n}} return string "{hexline(HIGH)}";\n')
print(f"wrote {out}/plain.id and {out}/shift.id (128 entries each)")
