#!/usr/bin/env bash
# Regenerate the measured numbers inside docs/TESTS.md's rollout status.
#
#   tools/statusgen.sh            # rewrite the block
#   tools/statusgen.sh --check    # exit 1 if rewriting would change anything
#
# Why this exists: docs/TESTS.md carried the line "Cases written so far: 0, of
# 6816". It was true when written and false four commits later, in the same
# session, because 200 cases had been written in idstd meanwhile. A status
# block that a human maintains is a status block that lies -- and this one was
# lying about the adoption of the very rule it describes.
#
# So the numbers are measured, written between markers, and checked by
# tests/run.sh. The prose around them stays hand-written; only the counts are
# generated, because only the counts go stale on their own.
#
# ../linux_id/docs/STATUS.md is where this idea comes from: it is generated and
# its own suite fails if the table and the measurement disagree. That is the
# best practice in this ecosystem and it should be the rule everywhere.
set -u
cd "$(dirname "$0")/.."

DOC=docs/TESTS.md
BEGIN='<!-- generated: adoption -->'
END='<!-- end generated -->'

# A case is a line of the form (args):(expected); a function declaration starts
# at column 0 with a name and an open paren. Both are counted the same way in
# every repository so the three numbers mean the same thing.
count_cases() { grep -rEch '^\([^)]*\) *: *\(' --include='*.id' "$@" 2>/dev/null | awk '{s+=$1} END {print s+0}'; }
count_fns()   { grep -rEh  '^[a-z_][a-z0-9_]*\(' --include='*.id' "$@" 2>/dev/null | wc -l; }

STD=../idstd
LINUX=../linux_id

here_c=$(count_cases compiler demos backends)
here_f=$(count_fns   compiler demos backends)
std_c=0; std_f=0
[ -d "$STD" ]   && { std_c=$(count_cases "$STD/core" "$STD/sys"); std_f=$(count_fns "$STD/core" "$STD/sys"); }
lin_c=0; lin_f=0
[ -d "$LINUX" ] && { lin_c=$(count_cases "$LINUX"); lin_f=$(count_fns "$LINUX"); }

have=$((here_c + std_c + lin_c))
need=$(( (here_f + std_f + lin_f) * 2 ))
pct=$(awk -v h="$have" -v n="$need" 'BEGIN { printf "%.1f", (n ? 100*h/n : 0) }')

block=$(cat <<EOF
$BEGIN
| repository | functions | cases written | cases needed (2 each) |
| --- | ---: | ---: | ---: |
| \`id_development\` | $here_f | $here_c | $((here_f * 2)) |
| \`idstd\` | $std_f | $std_c | $((std_f * 2)) |
| \`../linux_id\` | $lin_f | $lin_c | $((lin_f * 2)) |
| **total** | **$((here_f + std_f + lin_f))** | **$have** | **$need** |

**Adoption: $pct%.** Generated by \`tools/statusgen.sh\`; \`tests/run.sh\` fails
if it is stale. A repository with no \`.id\` beside this checkout counts zero.
$END
EOF
)

new=$(awk -v b="$BEGIN" -v e="$END" -v blk="$block" '
    $0 == b { print blk; skip = 1; next }
    $0 == e { skip = 0; next }
    !skip   { print }
' "$DOC")

if [ "$new" = "$(cat "$DOC")" ]; then
    [ "${1:-}" = "--check" ] && exit 0
    echo "statusgen: $DOC already current"
    exit 0
fi
if [ "${1:-}" = "--check" ]; then
    echo "statusgen: $DOC is out of date -- run tools/statusgen.sh" >&2
    exit 1
fi
printf '%s\n' "$new" > "$DOC"
echo "statusgen: wrote $DOC ($have of $need cases, $pct%)"
